version: '3'

services:
  php:
    image: bravado/php:7.3
    environment:
      - SMTP_SERVER
      - SMTP_USER
      - SMTP_PASS
    volumes:
      - ./tests:/var/www/html
    ports:
      - 8081:80
