FROM bravado/php:7.4

USER root

RUN export DEBIAN_FRONTEND=noninteractive && \
	curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
	echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
	curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
	apt-get install -y --no-install-recommends graphviz nodejs vim yarn git php7.4-xdebug php-pear make && \
	apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

# install composer
RUN curl -L https://getcomposer.org/installer | php -- --install-dir=/usr/bin

# enable ssl
RUN a2enmod ssl

# generate dummy certificate
RUN openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
	-subj "/C=BR/ST=Sao_Paulo/L=Sao_Paulo/O=Prosoma/CN=*.localhost" \
	-keyout /etc/apache2/ssl.key -out /etc/apache2/ssl.crt

# configure xdebug
RUN echo "xdebug.mode=debug" >> /etc/php/7.4/apache2/conf.d/20-xdebug.ini
ENV XDEBUG_CONFIG="client_host=172.17.0.1 client_port=9003"

USER app
